In [178]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating Tensors

Scaler

In [179]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [180]:
scaler.ndim

0

In [181]:
# Get tensors as python int
scaler.item()

7

In [182]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [183]:
vector.ndim

1

In [184]:
vector.shape

torch.Size([2])

In [185]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [186]:
MATRIX.ndim

2

In [187]:
MATRIX[0]

tensor([7, 8])

In [188]:
MATRIX.shape

torch.Size([2, 2])

In [189]:
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[6,7,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 9]]])

In [190]:
TENSOR.ndim

3

In [191]:
TENSOR.shape

torch.Size([1, 3, 3])

In [192]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 9]])

# Random Tensor

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.



`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [193]:
# create a random tensor of shape/ size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [194]:
random_tensor.ndim

2

In [195]:
# create a random tensor with simmilar shape to an image tensor
random_image_Size_tensor = torch.rand(size=(224,224,3))
random_image_Size_tensor.shape, random_image_Size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [196]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [197]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [198]:
ones.dtype

torch.float32

In [199]:
random_tensor.ndim

2

Creating a range of tensors and tensors-like

In [200]:
# use torch.range()
torch.range(0,10)
torch.arange(0,10)

/tmp/ipykernel_622/10463767.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [202]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes

**Note**: Tensors datatypes is one of the 3 big erros you will run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [203]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensors
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with thsi operations
float_32_tensor

tensor([3., 6., 9.])

In [204]:
float_32_tensor.dtype

torch.float32

In [205]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

Tensors application include
1. Addition
2. Subtraction
3. Multiplication
4. Divison
5. Matrix multiplication

In [206]:
# create a tensor
# Addition
tensor = torch.tensor([1,2,3])
tensor += 10
tensor

tensor([11, 12, 13])

In [207]:
# Multiply by 10
tensor = tensor*10
tensor

tensor([110, 120, 130])

In [208]:
# Subtract by 10
tensor - 10

tensor([100, 110, 120])

In [209]:
#In built functions
torch.mul(tensor,10)

tensor([1100, 1200, 1300])

In [210]:
torch.add(tensor,10)

tensor([120, 130, 140])

#Matrix multiplication
1. Element wise
2. Dot product

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
*`(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
*`(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
*`(3,2) @ (2,3)` -> `(3,3)`



In [211]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[2.5477, 2.5607, 2.4656],
        [3.1816, 2.9061, 2.7386],
        [2.4150, 2.5763, 3.0130]])

In [212]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([110, 120, 130]) * tensor([110, 120, 130])
Equals: tensor([12100, 14400, 16900])


In [213]:
torch.matmul(tensor,tensor)

tensor(43400)

In [214]:
tensor_A= torch.tensor([[1,2],
                        [3,4]
                        ,[5,6]])
tensor_B= torch.tensor([[7,8],
                        [9,10]
                        ,[11,12]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [215]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

#Finding the min,max,mean,sum, etc(tensor aggregation)

In [216]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [217]:
#Find the min
torch.min(x),
x.min()

tensor(0)

In [218]:
#Find the max
torch.max(x),
x.max()

tensor(90)

In [219]:
# Find the mean - note: the torch mean function requires tensor of float_32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [220]:
#Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

Finding the postional min and max

In [221]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [222]:
# Find the position in tensor that has the minimum value with argmin ->
# returns index postion of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [223]:
x[0]

tensor(0)

In [224]:
# Find the position in tensor that has the maximum value with argmin ->
# returns index postion of target tensor where maximum value occurs
x.argmax()

tensor(9)

## Reshaping, stacking, squezzing and unsequeezing tensors

* Reshaping - reshape an input to a defined shape
* View - Return a view of an input tensor of certain  shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (htack)
* Squeezzing - removes all '1' dimensions from a tensor
* Unsequeezing - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (Swapped) in a certain way

In [225]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [226]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [227]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [228]:
#Changing z changes x(because a view of a tensor ahares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [229]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [230]:
# torch.sequeeze() - removes all single dimensional from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [231]:
x_reshaped.shape

torch.Size([1, 9])

In [232]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [233]:
x_reshaped.squeeze().shape

torch.Size([9])

In [234]:
# torch.squeeze() - removes all 1D from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [235]:
# torch.unsqueeze() - adds a 1d to a target tensor at a specifix dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with torch.unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\n New tensor: {x_unsqueezed}")
print(f"\n New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

 New shape: torch.Size([9, 1])


In [236]:
# torch.permute - rearranges the dimension of target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height,width,colur_channels]

# permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

Indexing with pytorch is simmilar to indexing with numpy

In [237]:
#creating a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [238]:
# Lets index on a new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [239]:
# Lets index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [240]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [241]:
x[:, 0]

tensor([[1, 2, 3]])

In [242]:
# Get all values of 0 dimension and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [243]:
# Get all values of the 0 dimensions but only the 1 index of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [244]:
# Get index 0 of the 0th and 1st dimension and all the values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [245]:
# Index on x to return 9
x[0][2][2]
x[:,2,2]
# Index on x to return 3,6
x[0][1][2]
x[:,1,2]
x[0][0][2]
x[:,0,2]

tensor([3])

# Pytorch tensors & NUmpy

Numpy is a popular scientific Python numerical computing library.
And because of this, Pytorch has fuctionality to interact with it.

* Data in Numpy, want in Pytorch tensor -> torch.from_numpy(ndarray)

* Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [246]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

# Making array from numpy will create data type of float 64 where converting that intotensor while
# will also result in data type of float64, we can change data taype to
# float 32 by using type(torch.float32) . If we make an array with tensor it
# will result in datatype of float 32. It will reflect numpy default data type of float 64

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [247]:
array.dtype

dtype('float64')

In [248]:
tensor.dtype

torch.float32

In [249]:
# Change the value of array, what will this do to 'tensor'?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [250]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [251]:
# Change the tensor, what happens to 'numpy array'?
tensor = tensor + 1
array, numpy_tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random )

In short how a neural network learns:


`start with random no -> tensors operation -> update random no to try and make them better reprsentations of the data -> again -> again...`


To reduce randomness in neural networks and Pytorch comes the concept of a  random seed

In [252]:
torch.rand(3,3)

tensor([[0.0768, 0.7122, 0.3727],
        [0.8434, 0.7186, 0.8834],
        [0.2827, 0.5312, 0.5058]])

In [253]:
import torch

# create a two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0712, 0.1094, 0.4695, 0.2574],
        [0.9830, 0.6780, 0.1739, 0.0130],
        [0.6778, 0.0439, 0.4367, 0.4731]])
tensor([[0.9129, 0.0017, 0.1279, 0.2028],
        [0.6808, 0.9808, 0.8409, 0.7430],
        [0.3531, 0.0833, 0.1122, 0.4030]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [254]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
